/*****             GLOBAL FUNCTION PROTOTYPE SECTION                  ******/
DPCCALL void DPUM_PeekPokeSelMode(DPU_SCR_INFO *, DPU_PEEK_POKE_TYPE *, UINT8);
DPCCALL void DPUM_PeekPokeEntryMode1(DPU_SCR_INFO *, DPU_PEEK_POKE_TYPE *, UINT8);
DPCCALL void DPUM_PeekPokeEntryMode2(DPU_SCR_INFO *, DPU_PEEK_POKE_TYPE *, UINT8);

