DPCCALL BOOLEAN NV_WriteNvram(PDATAPUMP_CONTEXT pDatapump,UINT16 addr, const UINT8 *data, UINT16 size);
DPCCALL BOOLEAN NV_IsNvramBusy(PDATAPUMP_CONTEXT pDatapump);
DPCCALL BOOLEAN NV_ReadNvram(PDATAPUMP_CONTEXT pDatapump,UINT16 addr, UINT8 *data, UINT16 size);
